# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  - main  # Replace 'main' with your branch name if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Specify your desired Python version (e.g., '3.9')
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then
        pip install -r requirements.txt
      fi
    displayName: 'Install Dependencies'

  - script: |
      for file in $(find . -name "*.py"); do
        echo "Running $file"
        python "$file"
      done
    displayName: 'Execute Python Files'
